const nav = [
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 13:59:18',
        createUser: '91',
        deleteFlag: 1,
        faqId: '3',
        faqSortId: '1',
        manageCode: 'faq0002',
        manageCodeName: '可选购票周期',
        richTextHtml: '<p>阿胜打算打</p>',
        seqNum: 3,
        sortName: '班车购票类型',
        titleName: '测试新增222',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=3',
        updateName: 'admin',
        updateTime: '2022-11-11 14:05:53',
        updateUser: '91',
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:31:19',
        createUser: '91',
        deleteFlag: 1,
        faqId: '4',
        faqSortId: '1',
        manageCode: 'faq0001',
        manageCodeName: ' 班车购票类型',
        richTextHtml:
            '<p><span style="background-color: rgb(225, 60, 57);">班车购票类型--班车购票类型</span></p>',
        seqNum: 1,
        sortName: '班车购票类型',
        titleName: '班车购票类型--班车购票类型',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=4',
        updateName: '',
        updateTime: null,
        updateUser: null,
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:31:56',
        createUser: '91',
        deleteFlag: 1,
        faqId: '5',
        faqSortId: '1',
        manageCode: 'faq0002',
        manageCodeName: '可选购票周期',
        richTextHtml:
            '<p><span style="color: rgb(250, 250, 250); background-color: rgb(34, 7, 94);">班车购票类型--可选购票周期</span></p>',
        seqNum: 2,
        sortName: '班车购票类型',
        titleName: '班车购票类型--可选购票周期',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=5',
        updateName: '',
        updateTime: null,
        updateUser: null,
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:32:24',
        createUser: '91',
        deleteFlag: 1,
        faqId: '6',
        faqSortId: '1',
        manageCode: 'faq0003',
        manageCodeName: '选座',
        richTextHtml:
            '<p><span style="color: rgb(255, 255, 255); background-color: rgb(235, 144, 58);">班车购票类型--选座</span></p>',
        seqNum: 4,
        sortName: '班车购票类型',
        titleName: '班车购票类型--选座',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=6',
        updateName: 'admin',
        updateTime: '2022-11-11 15:32:30',
        updateUser: '91',
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:34:34',
        createUser: '91',
        deleteFlag: 1,
        faqId: '7',
        faqSortId: '1',
        manageCode: 'faq0004',
        manageCodeName: '老用户',
        richTextHtml:
            '<p><span style="background-color: rgb(255, 251, 143);">班车购票类型--老用户</span></p>',
        seqNum: 6,
        sortName: '班车购票类型',
        titleName: '班车购票类型--老用户',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=7',
        updateName: 'admin',
        updateTime: '2022-11-11 15:35:04',
        updateUser: '91',
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:34:34',
        createUser: '91',
        deleteFlag: 1,
        faqId: '7',
        faqSortId: '1',
        manageCode: 'faq0004',
        manageCodeName: '老用户',
        richTextHtml:
            '<p><span style="background-color: rgb(255, 251, 143);">班车购票类型--老用户</span></p>',
        seqNum: 6,
        sortName: '班车购票类型',
        titleName: '班车购票类型--老用户',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=7',
        updateName: 'admin',
        updateTime: '2022-11-11 15:35:04',
        updateUser: '91',
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:34:34',
        createUser: '91',
        deleteFlag: 1,
        faqId: '7',
        faqSortId: '1',
        manageCode: 'faq0004',
        manageCodeName: '老用户',
        richTextHtml:
            '<p><span style="background-color: rgb(255, 251, 143);">班车购票类型--老用户</span></p>',
        seqNum: 6,
        sortName: '班车购票类型',
        titleName: '班车购票类型--老用户',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=7',
        updateName: 'admin',
        updateTime: '2022-11-11 15:35:04',
        updateUser: '91',
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:34:34',
        createUser: '91',
        deleteFlag: 1,
        faqId: '7',
        faqSortId: '1',
        manageCode: 'faq0004',
        manageCodeName: '老用户',
        richTextHtml:
            '<p><span style="background-color: rgb(255, 251, 143);">班车购票类型--老用户</span></p>',
        seqNum: 6,
        sortName: '班车购票类型',
        titleName: '班车购票类型--老用户',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=7',
        updateName: 'admin',
        updateTime: '2022-11-11 15:35:04',
        updateUser: '91',
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:34:34',
        createUser: '91',
        deleteFlag: 1,
        faqId: '7',
        faqSortId: '1',
        manageCode: 'faq0004',
        manageCodeName: '老用户',
        richTextHtml:
            '<p><span style="background-color: rgb(255, 251, 143);">班车购票类型--老用户</span></p>',
        seqNum: 6,
        sortName: '班车购票类型',
        titleName: '班车购票类型--老用户',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=7',
        updateName: 'admin',
        updateTime: '2022-11-11 15:35:04',
        updateUser: '91',
    },
    {
        businessStatus: 2,
        createName: 'admin',
        createTime: '2022-11-11 15:34:34',
        createUser: '91',
        deleteFlag: 1,
        faqId: '7',
        faqSortId: '1',
        manageCode: 'faq0004',
        manageCodeName: '老用户',
        richTextHtml:
            '<p><span style="background-color: rgb(255, 251, 143);">班车购票类型--老用户</span></p>',
        seqNum: 6,
        sortName: '班车购票类型',
        titleName: '班车购票类型--老用户',
        uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=7',
        updateName: 'admin',
        updateTime: '2022-11-11 15:35:04',
        updateUser: '91',
    },
]

const sortList = [
    {
        businessStatus: 1,
        createName: 'admin',
        createTime: '2022-11-10 21:21:27',
        createUser: '57',
        deleteFlag: 1,
        faqId: '1',
        manageCode: 'faq0001',
        manageCodeName: ' 班车购票类型',
        richTextHtml: '<div><p>11</p><p>22</p><p>33</p></div>',
        seqNum: 1,
        sortId: '1',
        titleName: '班车购票类型说明',
        updateName: 'admin',
        updateTime: '2022-11-10 21:21:42',
        updateUser: '57',
    },
]

const testData = {
    businessStatus: 2,
    createName: 'admin',
    createTime: '2022-11-11 15:31:19',
    createUser: '91',
    deleteFlag: 1,
    faqId: '4',
    faqSortId: '1',
    manageCode: 'faq0001',
    manageCodeName: ' 班车购票类型',
    richTextHtml:
        '<p><span style="background-color: rgb(225, 60, 57);">班车购票类型--班车购票类型</span></p>',
    seqNum: 1,
    sortName: '',
    titleName: '班车购票类型--班车购票类型',
    uRL: 'https://cloud.ngrok.i84.com.cn/sspsFAQ.html?faqId=4',
    updateName: '',
    updateTime: null,
    updateUser: null,
}
